//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvvrb3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFollow
    {
        public int follower { get; set; }
        public int followed { get; set; }
    }
}
