//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvvrb3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlaylist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlaylist()
        {
            this.tblFavoritePlaylists = new HashSet<tblFavoritePlaylist>();
            this.tblPlaylistSongs = new HashSet<tblPlaylistSong>();
        }
    
        public int ID { get; set; }
        public string playlistTitle { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoritePlaylist> tblFavoritePlaylists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlaylistSong> tblPlaylistSongs { get; set; }
    }
}
