//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvvrb3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSong()
        {
            this.tblFavoriteSongs = new HashSet<tblFavoriteSong>();
            this.tblPlaylistSongs = new HashSet<tblPlaylistSong>();
        }
    
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public string songname { get; set; }
        public string songtracknum { get; set; }
        public string songartist { get; set; }
        public string songdescription { get; set; }
        public string src { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavoriteSong> tblFavoriteSongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlaylistSong> tblPlaylistSongs { get; set; }
    }
}
